Update Google Chrome install latest

diff --git a/Google Chrome install latest b/Google Chrome install latest
--- a/Google Chrome install latest
+++ b/Google Chrome install latest
@@ -16,11 +16,12 @@
 #	Version: 1.0
 #
 #	- Joe Farage, 17.03.2015
-#   - v.1.1 Top-Goodman, 19.07.2019: edited to ignore CPU architecture for non-intel based Macs in 2020
-#    Also gathering a little bit more info for the logs,
+#   - v.1.1 Spencer, 19.07.2019: edited to ignore CPU architecture for non-intel based Macs in 2020
+#    Also gathering a little bit more info for the logs, and preforming a version check pre-install
 #
 ####################################################################################################
-# Script to download and install Google Chrome.
+# Script to download and install Google Earth.
+# Only works on Intel systems.
 
 dmgfile="googlechrome.dmg"
 volname="Google Chrome"
@@ -30,29 +31,37 @@ url='https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg'
 /bin/echo "--" >>${logfile}
 if [ -d /Applications/Google\ Chrome.app ]; then
     currentinstalledver=$(/usr/bin/defaults read /Applications/Google\ Chrome.app/Contents/Info CFBundleShortVersionString)
-    /bin/echo "$(date): Current installed version is: $currentinstalledver" >>${logfile}
+    /bin/echo "Current installed version is: $currentinstalledver"
 else
-    /bin/echo "$(date): Google Chrome not found" >>${logfile}
+    /bin/echo "`date`: Google Chrome not found" >>${logfile}
 fi
-/bin/echo "$(date): Downloading latest version." >>${logfile}
+/bin/echo "`date`: Downloading latest version." >>${logfile}
 /usr/bin/curl -s -o /tmp/${dmgfile} ${url}
-/bin/echo "$(date): Mounting installer disk image." >>${logfile}
+/bin/echo "`date`: Mounting installer disk image." / >>${logfile}
 /usr/bin/hdiutil attach /tmp/${dmgfile} -nobrowse -quiet
-/bin/echo "$(date): Installing..." >>${logfile}
-ditto -rsrc "/Volumes/${volname}/Google Chrome.app" "/Applications/Google Chrome.app"
-/bin/sleep 10
-if [ -d /Applications/Google\ Chrome.app ]; then
-    newlyinstalledver=$(/usr/bin/defaults read /Applications/Google\ Chrome.app/Contents/Info CFBundleShortVersionString)
-    /bin/echo "$(date): SUCCESS: Google Chrome version ${newlyinstalledver} installed" >>${logfile}
-else
-    /bin/echo "$(date): ERROR: Google Chrome install unsuccessful, version remains at ${currentinstalledver}." >>${logfile}
-    /bin/echo "--" >>${logfile}
-    exit 1
+latestver=$(/usr/bin/defaults read /Volumes/"${volname}"/Google\ Chrome.app/Contents/Info.plist CFBundleShortVersionString)
+if [ "$currentinstalledver" != "$latestver" ]; then
+    /bin/echo "`date`: Current Google Chrome version: ${currentinstalledver}" >>${logfile}
+    /bin/echo "`date`: Latest Google Chrome version: ${latestver}" >>${logfile}
+    /bin/echo "`date`: Installing Google Chrome ${latestver}" >>${logfile}
+    ditto -rsrc "/Volumes/${volname}/Google Chrome.app" "/Applications/Google Chrome.app"
+    /bin/sleep 10
+    if [ -d /Applications/Google\ Chrome.app ]; then
+        newlyinstalledver=$(/usr/bin/defaults read /Applications/Google\ Chrome.app/Contents/Info CFBundleShortVersionString)
+        /bin/echo "`date`: SUCCESS: Google Chrome version ${newlyinstalledver} installed" >>${logfile}
+    else
+        /bin/echo "`date`: ERROR: Google Chrome install unsuccessful, version remains at ${currentinstalledver}." >>${logfile}
+        /bin/echo "--" >>${logfile}
+        exit 1
+    fi
+        else
+        /bin/echo "`date`: Firefox ESR is already up to date, running ${currentinstalledver}." >> ${logfile}
+        /bin/echo "--" >> ${logfile}
 fi
-/bin/echo "$(date): Unmounting installer disk image." >>${logfile}
+/bin/echo "`date`: Unmounting installer disk image." >>${logfile}
 /usr/bin/hdiutil detach $(/bin/df | /usr/bin/grep "${volname}" | awk '{print $1}') -quiet
 /bin/sleep 10
-/bin/echo "$(date): Deleting disk image." >>${logfile}
+/bin/echo "`date`: Deleting disk image." >>${logfile}
 /bin/rm /tmp/"${dmgfile}"
 /bin/echo "--" >>${logfile}
 exit 0
